services:
  console.app:
    class: Glassy::Console::Application
    kwargs:
      name: 'Glassy Framework'
      output: '@console.output'
      commands: '@console.command_list'

  console.input:
    class: Glassy::Console::ConsoleInput

  console.output:
    class: Glassy::Console::ConsoleOutput

tags:
  console.command:
    restriction: Glassy::Console::Command
